# -*- mode: yaml; coding: utf-8 -*-
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openhab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openhab
    spec:
      containers:
      - name: openhab
        image: openhab/openhab:3.0.2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8101
          name: console
          protocol: TCP
        volumeMounts:
        - name: etc-localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: openhab-conf
          mountPath: /openhab/conf
          readOnly: false
        - name: openhab-userdata
          mountPath: /openhab/userdata
          readOnly: false
        - name: openhab-addons
          mountPath: /openhab/addons
          readOnly: false
        - name: openhab-java
          mountPath: /openhab/.java
          readOnly: false
        - name: openhab-karaf
          mountPath: /openhab/.karaf
          readOnly: false
      volumes:
      - name: etc-localtime
        hostPath:
          path: /usr/share/zoneinfo/America/Los_Angeles
      - name: openhab-conf
        persistentVolumeClaim:
            claimName: /openhab/conf
      - name: openhab-userdata
        persistentVolumeClaim:
            claimName: /openhab/userdata
      - name: openhab-addons
        persistentVolumeClaim:
            claimName: /openhab/addons
      - name: openhab-java
        persistentVolumeClaim:
            claimName: /openhab/.java
      - name: openhab-karaf
        persistentVolumeClaim:
            claimName: /openhab/.karaf
      terminationGracePeriodSeconds: 300

# Local Variables:
# indent-tabs-mode: nil
# End:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-conf
  namespace: nodered
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
